name: brain_training
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  adaptive_dialog: ^2.1.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  dynamic_color: ^1.6.9
  envied: ^0.5.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.10
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  lottie: ^3.1.0
  material_color_utilities: ^0.8.0
  material_design_icons_flutter: ^7.0.7296
  nested: ^1.0.0
  responsive_framework: ^1.4.0
  riverpod_annotation: ^2.3.4
  settings_ui: ^2.0.2
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  pedantic_mono: ^1.26.0
  riverpod_generator: ^2.3.11

flutter:
  generate: true
  uses-material-design: true

  # Assets & Fonts
  # assets:
  #   - assets/images/
  #   - assets/lottie/
  # fonts:
  #   - family: CustomIcons
  #     fonts:
  #       - asset: assets/icons/CustomIcons.ttf
  #   - family: Murecho
  #     fonts:
  #       - asset: assets/fonts/Murecho-VariableFont_wght.ttf

# App Icon
# flutter_launcher_icons:
#   # https://zenn.dev/tsuruo/articles/eae9dbbad8372f#themed-app-icons
#   # https://blog.okaryo.io/20221127-support-themed-app-icon-in-flutter-app-for-android-13
#   android: true
#   ios: true
#   image_path: "assets/lancher_icons/AppIcon.png"
#   min_sdk_android: 21
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/lancher_icons/AppIcon_foreground.png"
#   # monochromeIconを作成する場合に以下を指定して一度生成する方法が一番楽かな？
#   # `/android/app/src/main/res/**/ic_launcher_foreground.png`を全て`ic_launcher_monochrome.png`にリネーム
#   # `android/res/mipmap-anydpi-v26/ic_launcher.xml`にmonochrome分を追加すれば完了
#   # adaptive_icon_foreground: "assets/lancher_icons/AppIcon_foreground_monochrome.png"

flutter_intl:
  enabled: true
